package com.lms_schoolapp.greenteam.model;

public enum AdminMenuOption {
    REGISTER_ADMIN,
    ACTIVE_USER,
    ACTIVE_USERS,
    DISPLAY_INACTIVE_USERS,
    CREATE_CLASS_SUBJECT,
    DISPLAY_ALL_SUBJECTS,
    ASSIGN_CLASS,
    DISPLAY_TEACHER_DETAIL,
    DISPLAY_ALL_BOOKS,
    ADD_BOOK,
    UPDATE_BOOK_DELETE,
    SEARCH_BOOK,
    DISPLAY_FORUMS_CREATE_THREAD,
    DISPLAY_THREADS,
    EXIT, CREATE_FORUM,

}
