package com.lms_schoolapp.greenteam.user.model;

public enum StudentMainMenuOption {
    DISPLAY_MANDATORY_BOOKS_PER_CLASS,
    DISPLAY_CLASSES_ASSIGNED,
    DISPLAY_TEACHERS_ASSIGNED,
    CHAT_WITH_STUDENTS,
    DISPLAY_FORUMS_CREATE_THREAD,
    DISPLAY_FORUMS, DISPLAY_THREADS,
    VISIT_WEB_SHOP,
    EXIT
}
